language: cpp
os:
  - linux
compiler:
  - g++
install:
  - sudo pip install codecov
script: # -C parameter is for MakefileDir
  - make
  - make test
  - make gcov
branches:
  only:
    - master
after_success:
  - codecov -X gcov
